let data = [
  {"ticker": "NIO", "name": "Nio"},
  {"ticker": "TSLA", "name": "Tesla"},
  {"ticker": "AAPL", "name": "Apple"},
  {"ticker": "MSFT", "name": "Microsoft"},
  {"ticker": "AMZN", "name": "Amazon"},
  {"ticker": "ZM", "name": "Zoom"},
  {"ticker": "GOOGL", "name": "Alphabet Class A"},
  {"ticker": "GOOG", "name": "Alphabet Class C"},
  {"ticker": "FB", "name": "Facebook"},
  {"ticker": "TSM", "name": "Taiwan Semiconductor Manufacturing"},
  {"ticker": "BABA", "name": "Alibaba"},
  {"ticker": "GM", "name": "General Motors"},
  {"ticker": "GME", "name": "GameStop"},
  {"ticker": "AMC", "name": "AMC Entertainment"},
  {"ticker": "ZTS", "name": "Zoetis"},
  {"ticker": "ABNB", "name": "Airbnb"},
  {"ticker": "TWTR", "name": "Twitter"},
  {"ticker": "HMC", "name": "Honda"},
  {"ticker": "SPOT", "name": "Spotify"},
  {"ticker": "FDX", "name": "FedEx"},
  {"ticker": "ROST", "name": "Ross"},
  {"ticker": "JPM", "name": "JPMorgan Chase"},
  {"ticker": "EMB", "name": "iShares JP Morgan USD Emerging Markets Bond ETF"},
  {"ticker": "AMJ", "name": "JPMorgan Ultra-Short Municipal Income ETF"},
  {"ticker": "JPST", "name": "JPMorgan Ultra-Short Income ETF"},
  {"ticker": "DOW", "name": "Dow"},
  {"ticker": "V", "name": "visa"},
  {"ticker": "DASH", "name": "DoorDash"},
  {"ticker": "RBLX", "name": "Roblox"},
  {"ticker": "KHC", "name": "Kraft Foods"},
  {"ticker": "JNJ", "name": "Johnson & Johnson"},
  {"ticker": "NVDA", "name": "NVIDIA"},
  {"ticker": "WMT", "name": "Walmart"},
  {"ticker": "KDP", "name": "Keurig Dr Pepper"},
  {"ticker": "PINS", "name": "Pinterest"},
  {"ticker": "SNAP", "name": "Snap"}, 
  {"ticker": "WBA", "name": "Walgreens"},
  {"ticker": "UNH", "name": "UnitedHealth"},
  {"ticker": "TWLO", "name": "Twilio"},
  {"ticker": "F", "name": "Ford Motor"},
  {"ticker": "BAC", "name": "Bank of America"},
  {"ticker": "MA", "name": "Mastercard"},
  {"ticker": "HD", "name": "Home Depot"},
  {"ticker": "PG", "name": "Procter & Gamble"},
  {"ticker": "DIS", "name": "Disney"},
  {"ticker": "EA", "name": "Electronic Artis"},
  {"ticker": "CMG", "name": "Chipotle"},
  {"ticker": "SRE", "name": "Sempra Energy"},
  {"ticker": "UBER", "name": "Uber"},
  {"ticker": "MAR", "name": "Mariott"},
  {"ticker": "LULU", "name": "Lululemon Athletica"},
  {"ticker": "PYPL", "name": "PayPal"},
  {"ticker": "ASML", "name": "ASML Holding"},
  {"ticker": "CMCSA", "name": "Comcast"},
  {"ticker": "XOM", "name": "Exxon Mobil"},
  {"ticker": "SONY", "name": "Sony"},
  {"ticker": "GE", "name": "General Electric"},
  {"ticker": "ROKU", "name": "Roku"},
  {"ticker": "ADBE", "name": "Adobe"},
  {"ticker": "KO", "name": "Coca-Cola"},
  {"ticker": "VZ", "name": "Verizon"},
  {"ticker": "ATVI", "name": "Activision Blizzard"},
  {"ticker": "TM", "name": "Toyota"},
  {"ticker": "INTC", "name": "Intel"},
  {"ticker": "ORCL", "name": "Oracle"},
  {"ticker": "CVS", "name": "CVS Health"},
  {"ticker": "ALL", "name": "Allstate"},
  {"ticker": "CSCO", "name": "Cisco"},
  {"ticker": "MNST", "name": "Monster"},
  {"ticker": "NFLX", "name": "Netflix"},
  {"ticker": "CRM", "name": "Salesforce"},
  {"ticker": "PFE", "name": "Pfizer"},
  {"ticker": "BCS", "name": "Barclays"},
  {"ticker": "RACE", "name": "Ferrari"},
  {"ticker": "NKE", "name": "Nike"},
  {"ticker": "SQ", "name": "Square"},
  {"ticker": "T", "name": "AT&T"},
  {"ticker": "ABT", "name": "Abbot Laboratories"},
  {"ticker": "PEP", "name": "Pepsi"},
  {"ticker": "CVX", "name": "Chevron"},
  {"ticker": "COIN", "name": "Coinbase"},
  {"ticker": "ABV", "name": "AbbVie"},
  {"ticker": "NVS", "name": "Novartis AG"},
  {"ticker": "WFC", "name": "Wells Fargo"},
  {"ticker": "AVGO", "name": "Broadcom"},
  {"ticker": "CVNA", "name": "Carvano"},
  {"ticker": "MRK", "name": "Merck"},
  {"ticker": "LLY", "name": "Eli Lilly"},
  {"ticker": "BHP", "name": "BHP Group"},
  {"ticker": "UPS", "name": "United Parcel Service"},
  {"ticker": "TMO", "name": "Thermo Fisher Scientific"},
  {"ticker": "DHR", "name": "Danaher"},
  {"ticker": "NVO", "name": "Novo Nordisk"},
  {"ticker": "ACN", "name": "Accenture plc Class A"},
  {"ticker": "TMUS", "name": "T-Mobile"},
  {"ticker": "TXN", "name": "Texas Instruments"},
  {"ticker": "MCD", "name": "McDonald's"},
  {"ticker": "MDT", "name": "Medtronic"},
  {"ticker": "MS", "name": "Morgan Stanley"},
  {"ticker": "COST", "name": "Costco Wholesale"},
  {"ticker": "SAP", "name": "SAP SE"},
  {"ticker": "C", "name": "Citigroup"},
  {"ticker": "HON", "name": "Honeywell"},
  {"ticker": "UL", "name": "Unilever PLC"},
  {"ticker": "LIN", "name": "Linde"},
  {"ticker": "GIS", "name": "General Mills"},
  {"ticker": "XEL", "name": "Xcel Energy"},
  {"ticker": "TGT", "name": "Target"},
  {"ticker": "SNOW", "name": "Snowflake"},
  {"ticker": "SHOP", "name": "Shopify"},
  {"ticker": "BBL", "name": "BHP Group"},
  {"ticker": "QCOM", "name": "QUALCOMM"},
  {"ticker": "PM", "name": "Philip Morris"},
  {"ticker": "BUD", "name": "Anheuser-Busch Inbev"},
  {"ticker": "UNP", "name": "Union Pacific"},
  {"ticker": "AZN", "name": "AstraZeneca"},
  {"ticker": "MTCH", "name": "Match"},
  {"ticker": "RY", "name": "Royal Bank of Canada"},
  {"ticker": "DOCU", "name": "DocuSign"},
  {"ticker": "BMY", "name": "Bristol-Myers Squibb"},
  {"ticker": "BA", "name": "Boeing"},
  {"ticker": "NEE", "name": "NextEra Energy"},
  {"ticker": "CHTR", "name": "Charter Communications"},
  {"ticker": "CCIV", "name": "Churchill Capital"},
  {"ticker": "PLTR", "name": "Palantir Technologies"},
  {"ticker": "LI", "name": "Li Auto"},
  {"ticker": "XPEV", "name": "Xpeng"},
  {"ticker": "FUBO", "name": "Fubo"},
  {"ticker": "WKHS", "name": "Workhorse"},
  {"ticker": "RIO", "name": "Rio Tinto"},
  {"ticker": "HDB", "name": "HDFC Bank"},
  {"ticker": "SCHW", "name": "Charles Schwab"},
  {"ticker": "LOW", "name": "Lowe's"},
  {"ticker": "AMGN", "name": "Amgen"},
  {"ticker": "RTX", "name": "Raytheon Technologies"},
  {"ticker": "SBUX", "name": "Starbucks"},
  {"ticker": "BLK", "name": "BlackRock"},
  {"ticker": "SNY", "name": "Sanofi"},
  {"ticker": "SE", "name": "Sea Limited AMerican Depositary Shares"},
  {"ticker": "HSBC", "name": "HSBC Holdings"},
  {"ticker": "CAT", "name": "Caterpillar"},
  {"ticker": "TD", "name": "Toronto Dominion Bank"},
  {"ticker": "AXP", "name": "American Express"},
  {"ticker": "IBM", "name": "International Business Machines"},
  {"ticker": "AMAT", "name": "Applied Materials"},
  {"ticker": "GS", "name": "Goldman Sachs"},
  {"ticker": "CSAN", "name": "Cosan"},
  {"ticker": "TOT", "name": "Total"},
  {"ticker": "INTU", "name": "Intuit"}, 
  {"ticker": "MMM", "name": "3M"},
  {"ticker": "AMT", "name": "American Tower"},
  {"ticker": "JD", "name": "JD.com"}, 
  {"ticker": "CVS", "name": "CVS Health"},
  {"ticker": "DE", "name": "Deere & Company"},
  {"ticker": "DEO", "name": "Diaegeo"}, 
  {"ticker": "TGT", "name": "Target"},
  {"ticker": "EL", "name": "Estee Lauder"},
  {"ticker": "VALE", "name": "Vale"},
  {"ticker": "VLO", "name": "Valero"},
  {"ticker": "Real", "name": "The RealReal"},
  {"ticker": "LMT", "name": "Lockheed Martin"}, 
  {"ticker": "SQ", "name": "Square"},
  {"ticker": "ISRG", "name": "Intuitive Surgical"},
  {"ticker": "AMCR", "name": "Amcor PLC"},
  {"ticker": "AMCX", "name": "AMC Networks"},
  {"ticker": "DIT", "name": "Amcon Distributing"}, 
  {"ticker": "ZM", "name": "Zoom"},
  {"ticker": "ZI", "name": "ZoomInfo"},
  {"ticker": "GSK", "name": "GlaxoSmithKline"},
  {"ticker": "ANTM", "name": "Anthem"},
  {"ticker": "AMD", "name": "Advanced Micro Devices"},
  {"ticker": "SNAP", "name": "Snap"}, 
  {"ticker": "SNA", "name": "Snap-On"},
  {"ticker": "NTAP", "name": "NetApp"},
  {"ticker": "BKNG", "name": "Booking Holdings"},
  {"ticker": "SYK", "name": "Stryker"}, 
  {"ticker": "UBER", "name": "Uber"},
  {"ticker": "MU", "name": "Micron"},
  {"ticker": "NOW", "name": "ServiceNow"},
  {"ticker": "LCRX", "name": "Lam Research"},
  {"ticker": "FIS", "name": "Fidelity"},
  {"ticker": "SPGI", "name": "S&P Global"},
  {"ticker": "MO", "name": "Altria"},
  {"ticker": "USB", "name": "US Bank"},
  {"ticker": "MDLZ", "name": "Mondelez International"},
  {"ticker": "BTI", "name": "British American Tobacco Industry"},
  {"ticker": "BP", "name": "BP plc"},
  {"ticker": "CI", "name": "Cigna"},
  {"ticker": "PLD", "name": "Prologis"}, 
  {"ticker": "ADP", "name": "Automatic Data Processing"},
  {"ticker": "TFC", "name": "Truist Financial"},
  {"ticker": "GILD", "name": "Gilead Sciences"},
  {"ticker": "PNC", "name": "PNC Financial Services Group"},
  {"ticker": "INFY", "name": "Infosys"},
  {"ticker": "CCI", "name": "Crown Castle International"},
  {"ticker": "BNS", "name": "Bank of Nova Scotia"},
  {"ticker": "TJX", "name": "TJX Companies"},
  {"ticker": "CNI", "name": "Canadian National Railway"},
  {"ticker": "BAM", "name": "Brookfield Asset Management"},
  {"ticker": "NTES", "name": "NetEase"},
  {"ticker": "CME", "name": "CME Group"},
  {"ticker": "CB", "name": "Chubb Limited"},
  {"ticker": "FISV", "name": "Fiserv"},
  {"ticker": "CSX", "name": "CSX Corporation"},
  {"ticker": "PTR", "name": "PetroChina"},
  {"ticker": "SHW", "name": "Sherwin-Williams"},
  {"ticker": "DELL", "name": "Dell"},
  {"ticker": "COP", "name": "ConocoPhillips"},
  {"ticker": "WBK", "name": "Westpac Banking"},
  {"ticker": "MUFG", "name": "Mitsubishi"},
  {"ticker": "MRNA", "name": "Moderna"},
  {"ticker": "ITW", "name": "Illinois Tools Works"},
  {"ticker": "SAN", "name": "Banco Santander"},
  {"ticker": "COF", "name": "Capital One Financial"},
  {"ticker": "EQNR", "name": "Equinor"},
  {"ticker": "HCA", "name": "HCA HealthCare"},
  {"ticker": "CL", "name": "Colgate"},
  {"ticker": "CPNG", "name": "Coupang"},
  {"ticker": "MMC", "name": "Marsh & McLennan"},
  {"ticker": "BDX", "name": "Becton, Dickinson & Company"},
  {"ticker": "NSC", "name": "Norfolk Southern Corporation"},
  {"ticker": "ABB", "name": "Abb Ltd"},
  {"ticker": "BIDU", "name": "Baidu"},
  {"ticker": "BMO", "name": "Bank of Montreal"},
  {"ticker": "MELI", "name": "MercadoLibre"},
  {"ticker": "SO", "name": "Southern Company"},
  {"ticker": "PBR", "name": "Petroleo Brasileiro"},
  {"ticker": "APD", "name": "Air Products and Chemicals"},
  {"ticker": "VMW", "name": "Vmware"},
  {"ticker": "EQIX", "name": "Equinix"},
  {"ticker": "SNP", "name": "China Petroleum & Chemical Corporation"},
  {"ticker": "BX", "name": "The Blackstone Group"},
  {"ticker": "ICE", "name": "Intercontinental Exchange"},
  {"ticker": "ADSK", "name": "Autodesk"},
  {"ticker": "MCO", "name": "Moody's"},
  {"ticker": "FCX", "name": "Freeport-McMoRan"},
  {"ticker": "IBN", "name": "ICICI Bank"},
  {"ticker": "BEKE", "name": "KE Holdings"},
  {"ticker": "ECL", "name": "Ecolab"},
  {"ticker": "D", "name": "Doiminion Energy"},
  {"ticker": "STLA", "name": "Stellantis"},
  {"ticker": "ADI", "name": "Analog Devices"},
  {"ticker": "LFC", "name": "China Life Insurance"},
  {"ticker": "BSX", "name": "Boston Scientific"},
  {"ticker": "EW", "name": "Edwards Lifesciences"},
  {"ticker": "WM", "name": "Waste Management"},
  {"ticker": "ILMN", "name": "Illumina"},
  {"ticker": "BSBR", "name": "Banco Santander Brasil"},
  {"ticker": "NOC", "name": "Northrop Grumman"},
  {"ticker": "TEAM", "name": "Atlassian"},
  {"ticker": "NXPI", "name": "NXP Semiconductors"},
  {"ticker": "PGR", "name": "Progressive"},
  {"ticker": "ETN", "name": "Eaton"},
  {"ticker": "UBS", "name": "UBS Group"},
  {"ticker": "EMR", "name": "Emerson Electric"},
  {"ticker": "MET", "name": "MetLife"},
  {"ticker": "GPN", "name": "Globaal Payments"},
  {"ticker": "AON", "name": "Aon"},
  {"ticker": "HUM", "name": "Humana"},
  {"ticker": "PUK", "name": "Prudential Public"},
  {"ticker": "WDAY", "name": "Workday"},
  {"ticker": "ITUB", "name": "Itau Unibanco"},
  {"ticker": "ING", "name": "ING"},
  {"ticker": "ABEV", "name": "Ambev"},
  {"ticker": "CP", "name": "Canadian Pacific Railway"},
  {"ticker": "VRTX", "name": "Vertex Pharmaceuticals"},
  {"ticker": "SCCO", "name": "Southern Copper"},
  {"ticker": "TAK", "name": "Takeda Pharmaceutical"},
  {"ticker": "GD", "name": "General Dynamics"},
  {"ticker": "REGN", "name": "Regeneron Pharmaceuticals"},
  {"ticker": "CM", "name": "Canadian Imperial Bank of Commerce"},
  {"ticker": "VOD", "name": "Vodafone"},
  {"ticker": "EPD", "name": "Enterprise Products"},
  {"ticker": "PHG", "name": "Royal Philips"},
  {"ticker": "AMX", "name": "America Movil"},
  {"ticker": "RELX", "name": "RELX"},
  {"ticker": "AMOV", "name": "American Movil"},
  {"ticker": "SMFG", "name": "Sumitomo Mitsui"},
  {"ticker": "CRWD", "name": "CrowdStrike"},
  {"ticker": "TRP", "name": "TC Energy"},
  {"ticker": "LYG", "name": "Lloyds Banking"},
  {"ticker": "PSA", "name": "Public Storage"},
  {"ticker": "BBD", "name": "Banco Bradesco"},
  {"ticker": "BNTX", "name": "BioNTech"},
  {"ticker": "KLAC", "name": "KLA"},
  {"ticker": "DG", "name": "Dollar General"},
  {"ticker": "TRI", "name": "Thomson Reuters"},
  {"ticker": "JCI", "name": "Johnson Controls International"},
  {"ticker": "IDXX", "name": "IDEXX Laboratories"},
  {"ticker": "NGG", "name": "National Grid Transco"},
  {"ticker": "ROP", "name": "Roper"},
  {"ticker": "EOG", "name": "EOG Resources"},
  {"ticker": "ALGN", "name": "Align"},
  {"ticker": "STZ", "name": "Constellation Brands"},
  {"ticker": "IQV", "name": "IQVIA Holdings"},
  {"ticker": "BK", "name": "The Bank of New York Mellon"},
  {"ticker": "AIG", "name": "American International Group"},
  {"ticker": "DD", "name": "DuPont de Nemours"},
  {"ticker": "BCE", "name": "BCE"},
  {"ticker": "TEL", "name": "TE Connectivity"},
  {"ticker": "ERIC", "name": "Ericsson"},
  {"ticker": "LHX", "name": "L3Harris"},
  {"ticker": "INFO", "name": "IHS Markit"},
  {"ticker": "VEEV", "name": "Veeva Systems"},
  {"ticker": "LVS", "name": "Las Vegas Sands"},
  {"ticker": "EXC", "name": "Exelon"},
  {"ticker": "KMB", "name": "Kimberly-Clark"},
  {"ticker": "E", "name": "Eni"},
  {"ticker": "SLB", "name": "Schlumberger"},
  {"ticker": "TROW", "name": "T.Rowe Price"},
  {"ticker": "WIT", "name": "Wipro"},
  {"ticker": "AEP", "name": "American Electric Power"},
  {"ticker": "MCHP", "name": "Microchip Technology"},
  {"ticker": "CNC", "name": "Centene"},
  {"ticker": "GOLD", "name": "Barrick Gold"},
  {"ticker": "DLR", "name": "Digital Realty Trust"},
  {"ticker": "PPG", "name": "PPG"},
  {"ticker": "BBDO", "name": "Banco Bradesco"},
  {"ticker": "SPG", "name": "Simon Property Group"},
  {"ticker": "PRU", "name": "Prudential Financial"},
  {"ticker": "A", "name": "Agilent"},
  {"ticker": "KMI", "name": "Kinder Morgan"},
  {"ticker": "BBVA", "name": "Banco Bilbao"},
  {"ticker": "PATH", "name": "UiPath"},
  {"ticker": "SYY", "name": "Sysco"},
  {"ticker": "BAX", "name": "Baxter"},
  {"ticker": "CNQ", "name": "Canadian Natural Resources"},
  {"ticker": "CRH", "name": "CRH"},
  {"ticker": "APTV", "name": "Aptiv"},
  {"ticker": "BILI", "name": "Bilibili"},
  {"ticker": "MFC", "name": "Manulife"},
  {"ticker": "MPC", "name": "Marathon Petroleum"},
  {"ticker": "BIIB", "name": "Biogen"},
  {"ticker": "APH", "name": "Amphenol"},
  {"ticker": "TRV", "name": "Travelers"},
  {"ticker": "CARR", "name": "Carrier Global"},
  {"ticker": "PH", "name": "Parker-Hannifin"},
  {"ticker": "MFG", "name": "Mizuho"},
  {"ticker": "ALXN", "name": "Alexion"},
  {"ticker": "SNPS", "name": "Synopsys"},
  {"ticker": "MSCI", "name": "MSCI"},
  {"ticker": "CTSH", "name": "Cognizant"},
]

export default data;