let data = [
  {"ticker": "NIO", "name": "Nio"},
  {"ticker": "TSLA", "name": "Tesla"},
  {"ticker": "AAPL", "name": "Apple"},
  {"ticker": "MSFT", "name": "Microsoft"},
  {"ticker": "AMZN", "name": "Amazon"},
  {"ticker": "GOOGL", "name": "Alphabet Class A"},
  {"ticker": "GOOG", "name": "Alphabet Class C"},
  {"ticker": "FB", "name": "Facebook"},
  {"ticker": "TSM", "name": "Taiwan Semiconductor Manufacturing"},
  {"ticker": "BABA", "name": "Alibaba"},
  {"ticker": "JPM", "name": "JPMorgan Chase"},
  {"ticker": "EMB", "name": "iShares JP Morgan USD Emerging Markets Bond ETF"},
  {"ticker": "AMJ", "name": "JPMorgan Ultra-Short Municipal Income ETF"},
  {"ticker": "JPST", "name": "JPMorgan Ultra-Short Income ETF"},
  {"ticker": "V", "name": "visa"},
  {"ticker": "JNJ", "name": "Johnson & Johnson"},
  {"ticker": "NVDA", "name": "NVIDIA"},
  {"ticker": "WMT", "name": "Walmart"},
  {"ticker": "UNH", "name": "UnitedHealth"},
  {"ticker": "BAC", "name": "Bank of America"},
  {"ticker": "MA", "name": "Mastercard"},
  {"ticker": "HD", "name": "Home Depot"},
  {"ticker": "PG", "name": "Procter & Gamble"},
  {"ticker": "DIS", "name": "Disney"},
  {"ticker": "PYPL", "name": "PayPal"},
  {"ticker": "ASML", "name": "ASML Holding"},
  {"ticker": "CMCSA", "name": "Comcast"},
  {"ticker": "XOM", "name": "Exxon Mobil"},
  {"ticker": "ADBE", "name": "Adobe"},
  {"ticker": "KO", "name": "Coca-Cola"},
  {"ticker": "VZ", "name": "Verizon"},
  {"ticker": "TM", "name": "Toyota"},
  {"ticker": "INTC", "name": "Intel"},
  {"ticker": "ORCL", "name": "Oracle"},
  {"ticker": "CSCO", "name": "Cisco"},
  {"ticker": "NFLX", "name": "Netflix"},
  {"ticker": "CRM", "name": "Salesforce"},
  {"ticker": "WMT", "name": "Walmart"},
  {"ticker": "WMT", "name": "Walmart"},
  {"ticker": "WMT", "name": "Walmart"},
]

export default data;